version: "3.7"

services:
  database:
    image: postgres:14
    container_name: database
    ports:
      - ${PGPORT}:${PGPORT}
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${PGHOST}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

volumes:
  database: